services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - ./vault-agent/vault-agent.hcl:/vault/config/vault-agent.hcl
      - ./vault-agent/templates:/vault/templates
      - ./vault-agent/role_id:/vault/role_id
      - ./vault-agent/secret_id:/vault/secret_id
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/vault/config/vault-agent.hcl
    networks:
      - web-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro
    restart: unless-stopped
    ports:
      - 8805:8000
    volumes:
      - .:/app
      - /app/vendor # This prevents the host from overriding the vendor directory
      - ./vault-agent/templates/adaro_laravel.env:/app/.env
    networks:
      - web-network
    # Install dependencies and ensure proper permissions before starting
    command: >
      sh -c "
        if [ ! -d /app/vendor ]; then
          composer install --no-interaction --prefer-dist --optimize-autoloader
        fi &&
        mkdir -p /app/storage/framework/{sessions,views,cache} &&
        chmod -R 775 /app/storage /app/bootstrap/cache &&
        chown -R www-data:www-data /app/storage /app/bootstrap/cache &&
        php artisan octane:frankenphp
      "
networks:
  web-network:
    external: true
