services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - ./vault-agent/vault-agent.hcl:/vault/config/vault-agent.hcl
      - ./vault-agent/templates:/vault/templates
      - ./vault-agent/role_id:/vault/role_id
      - ./vault-agent/secret_id:/vault/secret_id
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/vault/config/vault-agent.hcl
    networks:
      - web-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro
    restart: unless-stopped
    ports:
      - 8805:8000
    volumes:
      - .:/app
      - ./vault-agent/templates/adaro_laravel.env:/app/.env
    networks:
      - web-network
    # Ensure cache directories exist and have proper permissions
    command: >
      sh -c "
        mkdir -p /app/storage/framework/{sessions,views,cache} &&
        chmod -R 775 /app/storage /app/bootstrap/cache &&
        chown -R www-data:www-data /app/storage /app/bootstrap/cache &&
        php artisan octane:frankenphp
      "
networks:
  web-network:
    external: true
