services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - ./vault-agent/vault-agent.hcl:/vault/config/vault-agent.hcl
      - ./vault-agent/templates:/vault/templates
      - ./vault-agent/role_id:/vault/role_id
      - ./vault-agent/secret_id:/vault/secret_id
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    entrypoint:
      - vault
      - agent
      - -config=/etc/vault-agent-config.hcl
    networks:
      - web-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro_laravel
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./vault-agent/templates/adaro_laravel.env:/app/.env
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

