services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - /home/akbar/docker/vault-agent-config.hcl:/etc/vault-agent-config.hcl
      - /home/akbar/docker/token:/etc/vault/token
      - /home/akbar/docker/secrets:/secrets
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/vault/config/vault-agent.hcl
    entrypoint:
      - vault
      - agent
      - -config=/etc/vault-agent-config.hcl

    networks:
      - web-network
    healthcheck:
      test: ["CMD", "test", "-f", "/secrects/adaro_laravel.env"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro-laravel
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy
    ports:
      - 8805:8000
    volumes:
      - .:/app
      - /app/vendor # This prevents the host from overriding the vendor directory
    networks:
      - web-network

networks:
  web-network:
    external: true
