services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - ../vault-agent.hcl:/etc/vault-agent.hcl
      - ../token:/etc/vault/token
      - ../secrets:/secrets
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/etc/vault-agent.hcl
    entrypoint:
      - vault
      - agent
      - -config=/etc/vault-agent.hcl
    networks:
      - web-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro-laravel
    restart: unless-stopped
    ports:
      - 8806:8000
    volumes:
      - .:/app
      - /app/vendor # This prevents the host from overriding the vendor directory
      - ../secrets/adaro_laravel.env:/app/.env
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
