services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - /home/admin/docker/vault-agent.hcl:/etc/vault-agent.hcl
      - /home/admin/docker/token:/etc/vault/token
      - /home/admin/docker/secrets:/secrets
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/etc/vault-agent.hcl
    entrypoint:
      - vault
      - agent
      - -config=/etc/vault-agent.hcl

    networks:
      - web-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro-laravel
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy
    ports:
      - 8805:8000
    volumes:
      - .:/app
      - /app/vendor # This prevents the host from overriding the vendor directory
    networks:
      - web-network

networks:
  web-network:
    external: true
