services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: adaro-vault-agent
    volumes:
      - ./vault-agent/vault-agent.hcl:/vault/config/vault-agent.hcl
      - ./vault-agent/templates:/vault/templates
      - ./vault-agent/role-id:/vault/role_id
      - ./vault-agent/secret-id:/vault/secret_id
    environment:
      - VAULT_ADDR=https://vault.telemetry-adaro.id
    command: vault agent -config=/vault/config/vault-agent.hcl
    networks:
      - web-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaro-laravel
    restart: unless-stopped
    depends_on:
      - vault-agent
    ports:
      - 8805:8000
    volumes:
      - .:/app
      - /app/vendor # This prevents the host from overriding the vendor directory
      #- ./vault-agent/templates/adaro_laravel.env:/app/.env
    networks:
      - web-network

networks:
  web-network:
    external: true
